export enum PredefinedIcons {
  ArrowCurvedLeft,
  Expand,
  BusinessInvoice,
  Check,
  CommunicationAddNew,
  CommunicationBell,
  CommunicationGear,
  CommunicationDelete,
  CommunicationDownArrow,
  CommunicationRightArrow,
  CommunicationFire,
  CommunicationLove,
  CommunicationNew,
  CommunicationStar,
  CommunicationRemove,
  CommunicationFind,
  CommunicationsAnalytics,
  CommunicationsBlank,
  CommunicationClock,
  ConstructionAlert,
  ConstructionBuilding,
  ConstructionGear,
  ConstructionPC,
  Redo,
  Undo,
  Download,
  Edit,
  Pencil,
  GraphicAdd,
  InterfaceSliders,
  DotsMenu,
  PlusRound,
  NextRound,
  PreviousRound,
  DeleteRound,
  Deny,
  DownloadButton,
  SandClock,
  Gear,
  Star,
  StarOutline,
  InProgress,
  Clock,
  Delete,
  Trash,
  UserConfig,
  GamePad,

  Pin,
  Unpin,

}

const PredefinedIconsMap = new Map<PredefinedIcons | string, string>([
  [PredefinedIcons.ArrowCurvedLeft, "true-Arrows_empty_curved_arrow_left"],
  [PredefinedIcons.Expand, "true-Arrows_thin_arrows_fullscreen_directions_full_screen"],
  [PredefinedIcons.BusinessInvoice, "true-BusinessandFinance_business_finance_invoice"],
  [PredefinedIcons.Check, "true-Check"],
  [PredefinedIcons.CommunicationAddNew, "true-Communication_chat_message_sms_add_new"],
  [PredefinedIcons.CommunicationBell, "true-Communication_chat_message_sms_bell_ring_notification"],
  [PredefinedIcons.CommunicationGear, "true-Communication_chat_message_sms_cog_settings_gear_config"],
  [PredefinedIcons.CommunicationDelete, "true-Communication_chat_message_sms_delete"],
  [PredefinedIcons.CommunicationDownArrow, "true-Communication_chat_message_sms_download"],
  [PredefinedIcons.CommunicationRightArrow, "true-Communication_chat_message_sms_forward_send"],
  [PredefinedIcons.CommunicationFire, "true-Communication_chat_message_sms_hot_flame_fire"],
  [PredefinedIcons.CommunicationLove, "true-Communication_chat_message_sms_love_heart_favourite"],
  [PredefinedIcons.CommunicationNew, "true-Communication_chat_message_sms_new"],
  [PredefinedIcons.CommunicationStar, "true-Communication_chat_message_sms_Star"],
  [PredefinedIcons.CommunicationRemove, "true-Communication_chat_message_sms_remove"],
  [PredefinedIcons.CommunicationFind, "true-Communication_chat_message_sms_search"],
  [PredefinedIcons.CommunicationsAnalytics, "true-Communication_chat_message_sms_stats_report_analytics"],
  [PredefinedIcons.CommunicationsBlank, "true-Communication_chat_message_sms_text"],
  [PredefinedIcons.CommunicationClock, "true-Communication_chat_message_sms_time_schedule_clock"],
  [PredefinedIcons.ConstructionAlert, "true-Construction_attention_alert"],
  [PredefinedIcons.ConstructionBuilding, "true-Construction_building"],
  [PredefinedIcons.ConstructionGear, "true-Construction_gear_cog_engineering_engine_machine"],
  [PredefinedIcons.ConstructionPC, "true-Construction_pc_computer_engineering"],
  [PredefinedIcons.Redo, "true-Email_forward_message_arrow_right"],
  [PredefinedIcons.Undo, "true-Email_reply_arrow_left_direction_undo"],
  [PredefinedIcons.Download, "true-FilesandFolders_file_download"],
  [PredefinedIcons.Edit, "true-GraphicDesign_pencil"],
  [PredefinedIcons.Pencil, "true-GraphicDesign_pencil"],
  [PredefinedIcons.GraphicAdd, "true-GraphicDesign_picture_add"],
  [PredefinedIcons.InterfaceSliders, "true-InterfaceElements_interface_ui_controls_sliders"],
  [PredefinedIcons.DotsMenu, "true-InterfaceElements_interface_ui_dots_menu"],
  [PredefinedIcons.PlusRound, "true-UIEssentials_button_circle_round_add"],
  [PredefinedIcons.NextRound, "true-UIEssentials_button_circle_round_arrow_next"],
  [PredefinedIcons.PreviousRound, "true-UIEssentials_button_circle_round_arrow_previous"],
  [PredefinedIcons.DeleteRound, "true-UIEssentials_trash_bin_delete"],
  [PredefinedIcons.Deny, "true-UIEssentials_deny"],
  [PredefinedIcons.DownloadButton, "true-UIEssentials_download"],
  [PredefinedIcons.SandClock, "true-UIEssentials_sand_clock_time"],
  [PredefinedIcons.Gear, "true-UIEssentials_settings_cog_gear"],
  [PredefinedIcons.Star, "true-UIEssentials_star"],
  [PredefinedIcons.StarOutline, "true-UIEssentials_star_outline"],
  [PredefinedIcons.InProgress, "true-UIEssentials_time_clock"],
  [PredefinedIcons.Clock, "true-UIEssentials_time_clock"],
  [PredefinedIcons.Delete, "true-UIEssentials_trash_bin_delete"],
  [PredefinedIcons.Trash, "true-UIEssentials_trash_bin_delete"],
  [PredefinedIcons.UserConfig, "true-Users_female_user_config_configuration"],
  [PredefinedIcons.GamePad, "true-Videogames_controller_joystick_games_video_console"],

  [PredefinedIcons.Pin, "true-UIEssentials_star"],
  [PredefinedIcons.Unpin, "true-UIEssentials_star_outline"],
]);

export const getIconString = (icon: PredefinedIcons | string): string => {
  if (PredefinedIconsMap.has(icon)) {
    return PredefinedIconsMap.get(icon);
  }
  return icon as string;
};
