version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  build-application:
    docker: 
      - image: mcr.microsoft.com/dotnet/sdk:3.1-buster

    steps:
      - checkout
      - run: 
          name: Install npm
          command:
            |
            apt-get update -yq \
              && apt-get install curl gnupg -yq \
              && curl -sL https://deb.nodesource.com/setup_10.x | bash \
              && apt-get install nodejs -yq
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
            apt update && apt install yarn

      - run: 
          name: Front-end Dependencies
          command: yarn install

      - run: 
          name: Front-end Test
          command: 
            |
            yarn run validate
            yarn run lint

      - run:
          name: Front-end Build
          command: yarn run build

      - run:
          name: Back-end Dependencies
          command: dotnet restore
          
      - run:
          name: Back-end Build
          command: dotnet build -c Release /property:Version=0.0.0.$CIRCLE_JOB

      - discord/status:
          fail_only: true
          failure_message: "Application: **$CIRCLE_JOB** job has failed!"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
          mentions: "@employees"

      - discord/status:
          success_only: true
          success_message: "Application: **$CIRCLE_JOB** updated successfully"
          webhook: "${DISCORD_STATUS_WEBHOOK}"

workflows:
  build_and_deploy:
    jobs:
      - build-application
